import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from './auth.service';

@Component({
  selector: 'app-admin-shell',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  template: `<div class="admin-shell"><aside class="sidebar"><a routerLink="/inicio" class="brand" aria-label="LiquorSoft, inicio">Liquor<span>Soft</span></a><p class="side-label">GESTIÓN</p><nav aria-label="Menú de gestión"><a routerLink="/dashboard" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }"><span aria-hidden="true">▦</span><span>Resumen</span></a>@if (auth.can('productos')) {<a routerLink="/productos" routerLinkActive="active"><span aria-hidden="true">▣</span><span>Productos</span></a>}@if (auth.can('inventario')) {<a routerLink="/inventario" routerLinkActive="active"><span aria-hidden="true">◫</span><span>Inventario</span></a>}@if (auth.can('ventas')) {<a routerLink="/ventas" routerLinkActive="active"><span aria-hidden="true">◌</span><span>Ventas</span></a>}</nav><a routerLink="/catalogo" class="back-link">← Ver catálogo público</a><button type="button" class="logout" (click)="auth.logout()">Cerrar sesión</button></aside><main class="admin-content"><ng-content></ng-content></main></div>`,
  styles: [`:host { display:block; min-height:100vh; } .admin-shell { min-height:100vh; display:flex; color:#f8fafc; background:#0b1120; } .sidebar { width:240px; flex:none; display:flex; flex-direction:column; padding:30px 18px; border-right:1px solid rgba(255,255,255,.07); background:#0f172a; } .brand { margin:0 14px 58px; color:#fff; font-size:1.5rem; font-weight:800; letter-spacing:-1px; text-decoration:none; } .brand span { color:#f59e0b; } .side-label { margin:0 14px 14px; color:#64748b; font-size:.64rem; font-weight:800; letter-spacing:1.8px; } nav { display:grid; gap:7px; } nav a { display:flex; gap:13px; align-items:center; padding:12px 14px; border-radius:9px; color:#94a3b8; font-size:.88rem; text-decoration:none; } nav a:hover,nav a.active { color:#fbbf24; background:rgba(245,158,11,.1); } .back-link { margin:auto 14px 10px; color:#64748b; font-size:.73rem; text-decoration:none; } .back-link:hover { color:#fbbf24; } .logout { margin:0 14px; padding:9px 0; border:0; color:#fca5a5; background:transparent; text-align:left; font:inherit; font-size:.73rem; cursor:pointer; } .admin-content { flex:1; min-width:0; } @media (max-width:900px) { .sidebar { width:190px; } } @media (max-width:600px) { .admin-shell { display:block; } .sidebar { width:100%; padding:18px; } .brand { display:inline-block; margin:0 0 18px; } .side-label,.back-link,.logout { display:none; } nav { display:flex; overflow:auto; } nav a { white-space:nowrap; } }`],
})
export class AdminShell { protected readonly auth = inject(AuthService); }
