import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from './auth.service';

@Component({
  selector: 'app-admin-shell',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  template: `<div class="admin-shell"><aside class="sidebar"><a routerLink="/inicio" class="brand">Liquor<span>Soft</span></a><div class="admin-identity"><span class="status-dot" aria-hidden="true"></span><div><strong>{{ auth.user()?.name }}</strong><small>Administrador</small></div></div><p class="side-label">GESTIÓN</p><nav>@if (auth.can('dashboard')) {<a routerLink="/admin/dashboard" routerLinkActive="active"><span>▦</span><span>Resumen</span></a>}@if (auth.can('productos')) {<a routerLink="/admin/productos" routerLinkActive="active"><span>▣</span><span>Productos</span></a>}@if (auth.can('categorias')) {<a routerLink="/admin/categorias" routerLinkActive="active"><span>◈</span><span>Categorías</span></a>}@if (auth.can('inventario')) {<a routerLink="/admin/inventario" routerLinkActive="active"><span>◫</span><span>Inventario</span></a>}@if (auth.can('ventas')) {<a routerLink="/admin/ventas" routerLinkActive="active"><span>◌</span><span>Ventas</span></a>}@if (auth.can('compras')) {<a routerLink="/admin/compras" routerLinkActive="active"><span>▤</span><span>Compras</span></a>}@if (auth.can('proveedores')) {<a routerLink="/admin/proveedores" routerLinkActive="active"><span>▥</span><span>Proveedores</span></a>}@if (auth.can('usuarios')) {<a routerLink="/admin/usuarios" routerLinkActive="active"><span>♙</span><span>Usuarios</span></a>}</nav><a routerLink="/productos" class="back-link">← Ver tienda</a><button type="button" class="logout" (click)="auth.logout()">Cerrar sesión</button></aside><main class="admin-content"><ng-content></ng-content></main></div>`,
  styles: [`:host{display:block;min-height:100vh}.admin-shell{min-height:100vh;display:flex;color:#f8fafc;background:#0b1120}.sidebar{width:270px;flex:none;display:flex;flex-direction:column;padding:30px 18px;border-right:1px solid rgba(255,255,255,.07);background:#0f172a}.brand{margin:0 14px 28px;color:#fff;font-size:1.5rem;font-weight:800;text-decoration:none}.brand span{color:#f59e0b}.admin-identity{display:flex;gap:10px;align-items:center;margin:0 8px 34px;padding:12px;border:1px solid rgba(255,255,255,.07);border-radius:10px;background:rgba(255,255,255,.03)}.admin-identity strong,.admin-identity small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.admin-identity strong{color:#e2e8f0;font-size:.75rem}.admin-identity small{margin-top:3px;color:#64748b;font-size:.65rem}.status-dot{width:8px;height:8px;flex:none;border-radius:50%;background:#4ade80;box-shadow:0 0 0 4px rgba(74,222,128,.12)}.side-label{margin:0 14px 14px;color:#64748b;font-size:.64rem;font-weight:800;letter-spacing:1.8px}nav{display:grid;gap:7px}nav a{display:flex;gap:13px;align-items:center;padding:12px 14px;border-radius:9px;color:#94a3b8;font-size:.88rem;text-decoration:none}nav a:hover,nav a.active{color:#fbbf24;background:rgba(245,158,11,.1)}.back-link{margin:auto 14px 10px;color:#64748b;font-size:.73rem;text-decoration:none}.logout{margin:0 14px;padding:9px 0;border:0;color:#fca5a5;background:transparent;text-align:left;font:inherit;font-size:.73rem;cursor:pointer}.admin-content{flex:1;min-width:0}@media(max-width:600px){.admin-shell{display:block}.sidebar{width:100%;padding:18px}.brand{display:inline-block;margin:0 0 18px}.admin-identity{margin:0 0 18px}.side-label{display:none}.back-link,.logout{display:none}nav{display:flex;overflow:auto}nav a{white-space:nowrap}}`],
})
export class AdminShell {
  protected readonly auth = inject(AuthService);
}
